PrestaShop/prestashop-flashlight

- assets/mariadb-server.cnf
- assets/run.sh
> MySQL enhancements

- Dockerfile
- README.md
| Description?      | With apk (Dockerfile), `gnu-libiconv-libs` doesn't work anymore. I replaced it with `gnu-libiconv`
| How to test?      | Enjoy with the build script
> fix(docker): Replace gnu-libiconv-libs by gnu-libiconv

- .dockerignore
- .github/workflows/docker-publish.yml
- build.sh
Previously, build.sh was only generating "latest" as a valid tag. This fixes it.
> Fix build tag generation

- assets/nginx.conf
Redirecting should be performed with a 302, otherwise /ps-admin won't be resolved as index.php or will mess up with relative paths.
> fix(run): nginx redirect fix

- .github/workflows/docker-publish.yml
This package will never have such thing as "versioning" as this is a pure bundler, not a product in essence.
> chore(github): Disable push by tag

- assets/patch.sh
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
The `mcrypt` PHP extension was missing, hence the errors with the PS 1.6 backoffice.
> fix(build): Add mcrypt extension to fix PrestaShop 1.6 RIJNDAEL required by back-office

- build.sh
The `:latest` tag was not set yet, hence very useful for developers. The latest tag sounds for the latest PrestaShop version officially released, and stands for an alpine linux build with nginx.
> chore(build): fix latest docker tag

- README.md
- assets/run.sh
- examples/README.md
- examples/with-custom-scripts/README.md
- examples/with-custom-scripts/docker-compose.yml
- examples/with-custom-scripts/init-scripts/01-bretzel.sh
- examples/with-custom-scripts/init-scripts/02-tarte-flambee.sh
> fix(run): custom script runner

- build.sh
| Description?      | Getting tags with the PrestaShop version is more handy, and will stand for the default OS_FLAVOUR (alpine linux) and for the recommended PHP version.
| Type?             | packaging
| How to test?      | ./build.sh && docker images
> chore(build): PS_VERSION as a tag if the recommended PHP version is used

- README.md
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
- php-flavours.json
PHP CS fixer is usually used to lint PHP files.
> feat(tooling): add php-cs-fixer

- README.md
- build.sh
| Description?      | When the PHP version is the recommended PHP version and when the OS_FLAVOUR is the default one, the build.sh script will also generate a `php-x.y` tag. If PrestaShop 8.1 has PHP 8.1 recommended, the `php:8.1` tag will be bound to this image.
| How to test?      | docker pull prestashop/prestashop-flashlight:php-8.1
> chore(packaging): publish a php-x.y tag

- docker/alpine.Dockerfile
- docker/debian.Dockerfile
| Description?      | When you use composer after dropping rights to www-data, you cannot save the composer cache in the root location. Therefore defining $COMPOSER_HOME may help if you intend to use composer calls in any init-scripts or post-scripts.
| How to test?      | call `composer install` in an init-script
> chore(composer): set rights for www-data to modify $COMPOSER_HOME

- assets/hydrate.sh
- assets/run.sh
| Description?      | If you want to mount the whole $PS_FOLDER directory while running PrestaShop Flashlight, you may encounter issues. Either (1) your local configuration could be overriden and lost or (2), you would miss any configuration. For (1) we perform a backup file, and (2) search for a built version of the parameters to write it in your local volume. Such usage was not expected in early design stages of Flashlight, but are welcome to provide new use cases.
| Type?             | new feature
| Sponsor company   | The Core team
| How to test?      | Mount your PrestaShop sources in flashlight with a docker volume to try it …
> feat(run): ease mounting $PS_FOLDER entirely

- assets/run.sh
| Description?      | This minor fix correct the way messages are displayed: if you do not have a post-script or no init-script, the proper warning will be echoed to the run.sh output.
| How to test?      | Run flashlight without init nor post scripts, and check you have "* No init-script(s) found" in your output.
> fix(run): unprecise script lock checks

- README.md
- build.sh
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
- release.sh
A subtle issue was raised during the docker image publish operation, but was not catched by the CI checks.
This is because TARGET_PLATFORM was used as a combined string "linux/arm64,linux/amd64", and could not correctly be parsed in the Dockerfiles scripts.
To really solve this issue, I found more relevant to definitely rely on the OS than to provide error prone external variables : using `arch` command helps to figure out which arch is running during the Dockerfile build... Even in platform compatibility mode (target arch != build arch).
> fix(build): target platform is no longer a build-arg

- assets/run.sh
For auto-install modules: Get the module name from the root archive directory
> Fix: get module name from root archive directory

- build.sh
- prestashop-versions.json
@nicosomb I have issues while x-compiling to aarch64 on Alpine. This prevent me from releasing new images of flashlight, which is cumbersome.
If this is not an issue to your use case, I would like to diminish the node.js footprint, as it grabs python3 and an infinite number of dependencies with it.
After this one, I'll have a look at the PrestaShop core, if it's doable to extend Node.js compatibility up to 20.10 LTS.
> fix(build): [breaking] only ship Node.js for PrestaShop >= 8.0

- .github/workflows/pull-request.yml
- README.md
- assets/hydrate.sh
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
| Description?      | Fixes https://github.com/PrestaShop/prestashop-flashlight/issues/48, there is a known issue on cross-compilation issue that was present since the introduction of the Node.js toolkit. <br><br>My previous attempt to port Node.js to Flashlight was overly complicated, and did not relied on the distributions (alpine or debian). That's a pitty because there're aimed precisely for resolving dependencies. <br><br> PrestaShop source code is not yet compatible to the latest 18.x and 20.x branches of Node.js. However we can change that.<br><br> Flashlight now ships also cross-compilation test to avoid such pain at release time in the future.<br><br><br>**Note:** …
> fix(chore): fixes #48 add a cross-compilation test

- .github/workflows/pull-request.yml
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
Building gd is different from a PHP version to another. 2 more exceptions had to be added to handle PHP 7.2 and 7.3.
> fix(build): support for PHP 7.2 and PHP 7.3

- .github/workflows/pull-request.yml
- build.sh
| Description?      | the latest tag only apply to the latest PS_VERSION and the recommended PHP_VERSION
| Fixed ticket?     | Fixes #61
| Sponsor company   | Mikatux corp
| How to test?      | `DRY_RUN=1 PS_VERSION=8.1.3 PHP_VERSION=7.2 ./build.sh \| grep -v ':latest'`
> fix(build): the latest tag was misgiven

- assets/nginx.conf
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
| Description?      | Usually modules can be big. 20M should be more than enough.
| Fixed ticket?     | Fixes #68 #66
| Sponsor company   | PrestaShop (@thymotep)
| How to test?      | Upload a <20M module, and check server info in PrestaShop Back Office.
> Move from 8M to 20M to support more modules

- .gitignore
- examples/basic-example/README.md
- examples/basic-example/docker-compose.yml
- examples/develop-a-module/README.md
- examples/develop-a-module/docker-compose.yml
- examples/develop-a-module/init-scripts/module-install.sh
- examples/develop-a-module/modules/testmodule/composer.json
- examples/develop-a-module/modules/testmodule/composer.lock
- examples/develop-a-module/modules/testmodule/config.xml
- examples/develop-a-module/modules/testmodule/index.php
- examples/develop-a-module/modules/testmodule/testmodule.php
- examples/develop-prestashop/README.md
- examples/ngrok-tunnel/README.md
- examples/with-init-scripts/README.md
- examples/with-post-scripts/README.md
| Description?      | Make the examples work better, in particular the develop-a-module, with the installation script provided.
| How to test?      | open ./examples/develop-a-module/README.md
> Enhance examples

- .gitignore
- release.sh
| Description?      | Automates the automated build process: now guess all the tags and image combination we wish to build every time flashlight is updated. Also build images for major.minor versions of PrestaShop from 7 to 8+, and major.minor.patch for 1.6. Build images with recommended AND compatible versions of PHP.
| Type?             | new feature
| Fixed ticket?     | Fixes #60
| How to test?      | ./release.sh
> fea(release.sh): automates compatible & recommended php versions

- .github/workflows/pull-request.yml
| Description?      | PrestaShop 8.1.4 has just been released: https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.4.
> minor(env): test prestashop-flashlight with the latest release

- .github/workflows/nightly-cron-publish.yml
- README.md
- build.sh
- examples/basic-example/README.md
- examples/nightly-example/README.md
- examples/nightly-example/docker-compose.yml
| Description?      | Add a CRON job to build and publish a nightly. Latest zip I opened was build at 1:27 GMT, I guess setting the CRON job for 2 am GMT will do the job.
| Type?             | improvement.
> chore(ci): add a cron job every night at 2 to publish the nightly

- .github/workflows/docker-publish.yml
- .github/workflows/nightly-cron-publish.yml
- .github/workflows/pull-request.yml
Github action default timeout for jobs is 6h.
This is a waste of money, no job would be ever this long.
> chore(ga): define timeouts to avoid 6h timeout

- assets/run.sh
| Description?      | Fix ngrock example with - PS_DOMAIN=localhost:8000
| How to test?      | docker compose up -d
> fix(examples): Missing PS_DOMAIN on ngrok

- .github/workflows/nightly-cron-publish.yml
| Description?      | The nightly build is still having issues, this PR tries to simplify the workflow and fix the multiaarch build that might be the reason of the stucked job.
| Fixed ticket?     | Fixes #83
| How to test?      | Run the Action
> Fix nightly cron build

- assets/alpine-base-install.sh
| Description?      | Make is really useful when it comes to orchestrate build & test commands for PrestaShop modules. It was unexpectedly removed from flashlight last week.
| How to test?      | `docker run -it --rm --entrypoint sh prestashop/prestashop-flashlight:8.1.5-alpine -c 'which make'`
> fix(alpine): revert back make to alpine images

- assets/hydrate.sh
- examples/xdebug-prestashop/docker-compose.yml
| Description?      | The nightly zip contains an "admin" folder. Once detected by the nightly installer this will be transformed in something like `admin123t4uiuqvaq7huqffv` which obviously we do not want: our documentation specifies `admin-dev` as the back-office endpoint.
| Type?             | bug fix 
| How to test?      | `PS_VERSION=nightly ./build.sh`
> fix(build): nightly mess with PS_FOLDER_ADMIN

- assets/hydrate.sh
| Description?      | As you might noticed, nightly builds were stopping on error, due to timeout. I could not reproduce the issue on an arm64 setup, so did I tried on an amd64 one. I could reproduce and identify the tiny bits.
| How to test?      | `PS_VERSION=nightly ./build.sh`
> fix(build): hanging mysqld startup and connectivity check

- examples/auto-install-modules/docker-compose.yml
- examples/basic-example/docker-compose.yml
- examples/cloudflared-tunnel/docker-compose.yml
- examples/develop-a-module/docker-compose.yml
- examples/develop-prestashop/docker-compose.yml
- examples/ngrok-tunnel/docker-compose.yml
- examples/nightly-example/docker-compose.yml
- examples/with-init-scripts/docker-compose.yml
- examples/with-post-scripts/docker-compose.yml
- examples/xdebug-prestashop/docker-compose.yml
| Description?      | Mariadb LTS recently changed, and our healthcheck assumptions in the docker-compose examples are now wrong. This adjustment simplifies and restore the way Flashlight will wait Mariadb to be healthy & running before starting.
| Fixed ticket?     | Fixes #110
| How to test?      | `cd ./examples/basic-example && docker-compose up`
> Review healthchecks for mariadb:lts

- assets/nginx.conf
- assets/run.sh
| Description?      | Some users target paths like `stuff/` instead of `stuff/index.php`, especially in the PrestaShop modules' ecosystem. PUT & DELETE http verbs may suffer from the previous configuration, and this new one may resolve some hard to diagnose issues.
| Fixed ticket?     | Fixes #111
| Sponsor company   | PrestaShop Account
| How to test?      | Onboard & offboard PS Accounts.
> fix(build): nginx configuration

- .github/workflows/pull-request.yml
- assets/alpine-base-install.sh
- assets/debian-base-install.sh
- assets/hydrate.sh
- assets/php-configuration.sh
- build.sh
- php-flavours.json
| Description?      | My colleague needs a testing Flashlight instance for PS 1.6 with PHP 5.6. This build cannot be currently performed yet.
| Type?             | new feature
| How to test?      | `PS_VERSION=1.6.1.21 PHP_VERSION=5.6 ./build.sh`
> feat(build): add PHP<7.1 support to PS 1.6

- README.md
- php-flavours.json
| Description?      | This PHP 5.5 recently introduced is not working, so better drop it than letting it here. Explanations / motivations on how hard and unrewardful this PHP support prior to 5.6 could be.
| Type?             | refactor
| BC breaks?        |  no
> fix(build): drop PHP 5.5 support

- assets/debian-base-install.sh
- assets/run.sh
| Description?      | Debian builds were not working for PHP 5.6 (ex: PS 1.6.1.24). This PR aims at fixing this, but also fixing a bug on `find`, old distributions does not ship such command which support `-executable` as an argument
| Fixed ticket?     | Fixes #120 #122
| How to test?      | `OS_FLAVOUR=debian PS_VERSION=1.6.1.24 ./build.sh`
> fix(build): Debian build for PHP 5.6

- assets/run.sh
| Description?      | set absolute path for bin/console call when auto installing module
| Fixed ticket?     | Fixes #{https://github.com/PrestaShop/prestashop-flashlight/issues/118}
| How to test?      | Run the auto install module example
> absolute path for bin/console when auto installing module

- README.md
- assets/alpine-base-install.sh
- assets/debian-base-install.sh
- assets/nginx.conf
- assets/php-fpm.conf
- assets/run.sh
- docker/alpine.Dockerfile
- docker/debian.Dockerfile
- prestashop-versions.json
| Description?      | PrestaShop Flashlight used to be run as root, dropping rights to www-data when necessary (to run init-scripts or post-scripts). The often lead to confusion, developers used to use the PrestaShop CLI under root rights, locking files for the www-user in /var/www/html/modules, or the cache files for instance. <br /><br />I had the choice between completely dropping www-data (thus running everything as root), or going deeper in the rabbit hole, and publish a "secured-by-default" version of Flashlight, running the container with user www-data by default. This last option has been chosen. I hope this won't break anything on your end - it should not. <br /><br />You …
> fix: all-in with www-data user

- assets/alpine-base-install.sh
- assets/debian-base-install.sh
| Description?      | As suggested by the community, would be easier for Linux users to have already a 1000 www-data user, which would help while mounting local files to the docker container.
| Fixed ticket?     | Fixes #99
| How to test?      | `docker run -it --rm --entrypoint sh prestashop/prestashop-flashlight id` would give 1000.
> fix: set uid gid of www-data to 1000

- assets/hydrate.sh
- assets/patch.sh
| Description?      | PrestaShop 1.6 uses deprecated cipher methods, this disables it from the configuration, and avoid flooding the logs and getting html in json responses...
| Fixed ticket?     | Fixes #129
> fix(build): 1.6  logs flooded by mcrypt_decrypt()

- .github/workflows/pull-request.yml
- README.md
- assets/alpine-base-install.sh
- assets/debian-base-install.sh
- assets/hydrate.sh
- build.sh
- docker/alpine-base.Dockerfile
- docker/flashlight.Dockerfile
- php-flavours.json
- release-base.sh
- release.sh
| Description?      | Fix the build of images with old distros for PHP 5.6 and add more tests in the CI workflow.
| Type?             | bug fix + enhancements
| BC breaks?        | **yes**. `CUSTOM_BASE_IMAGE` has been removed, as this behavior is now configurable for both base and final images through `TARGET_IMAGE` or `TARGET_IMAGE_NAME` + `TARGET_IMAGE_TAG` (new)
| Deprecations?     | no, but as the build script API change, please do not use `CUSTOM_BASE_IMAGE` nor `--custom-base-image` starting from now
| Fixes      | PrestaShop 8.3 now proposes a `parameters.yml.dist` file. TARGET_IMAGE related fixes confusing with base image variables.
| How to test?      | BASE_ONLY=true …
> fix(build): old base image

- .github/workflows/pull-request.yml
- assets/alpine-base-install.sh
- assets/debian-base-install.sh
- assets/php-configuration.sh
| Description?      | Xdebug was disabled in php.ini before it was installed
| Sponsor company   | Prestashop
> Fixed disabling xdebug too early
