PrestaShop/prestashop-flashlight

LICENCE

MIT sounds more flexible as a licence to welcome contributions.
@Venatum do you agree with this relicencing? We are the only 2 contributors as of today.

Move to MIT Licence

---

.github/docker-publish.yml
build.sh

Introduce a new script to manually deploy flashlight to prestashop/prestashop-flashlight on the Docker registry.

Add a github action script

---

.gitignore
Dockerfile
build.sh

| Description?      | Add some labels & code update reported by Sonar
| How to test?      | `./build.sh`

feat(docker): Add some labels

---

.github/workflows/docker-publish.yml
Dockerfile
README.md
assets/nginx.conf
assets/run.sh
build.sh
docker-compose.yml

fix(build): various enhancements

---

.github/workflows/docker-publish.yml

A minor fix to enhance the job names and env definition

fix(GA): enhance naming and env

---

assets/run.sh

A previous issue was introduced, letting module installation and custom script be run without dropping root privileges. 
This was causing PrestaShop sympfony's cache to be pre-filled with content owned by root only, and crashing at first run.

fix(run.sh): only use www-data rights to start scripts

---

build.sh

chore(build): pull before cache

---

docker-compose.yml
docker/alpine.Dockerfile
docker/debian.Dockerfile
examples/README.md
examples/auto-install-modules/README.md
examples/auto-install-modules/docker-compose.yml
examples/with-custom-scripts/README.md
examples/with-custom-scripts/docker-compose.yml

* Do not bind MySQL port in docker compose examples
* Add auto-install-modules example
* Simplify healthchecks

chore(documentation): Add auto-install-modules example

---

build.sh

| Description?      |  - Add `DEFAULT_PLATFORM` - Remove get_tag - Update docker cache
| Type?             | improvement / refactor
| BC breaks?        |  no
| How to test?      | Enjoy `build.sh`

feat(build): Some improvements

---

docker/alpine.Dockerfile
docker/debian.Dockerfile

make is a classic tool, easy to use and to install: let's ship it

feat(toolbox): add make support

---

.env.dist

| Description?      | Micro fix of a typo :)

Fix of typo in .env.dist

---

README.md
examples/README.md
examples/develop-a-module/README.md
examples/develop-prestashop/README.md
examples/develop-prestashop/docker-compose.yml
examples/develop-prestashop/init-scripts/build-assets.sh
examples/with-init-scripts/README.md
examples/with-post-scripts/README.md

| Description?      | Flashlight is closer than ever to be able to provide a complete development environment suitable for a PrestaShop Core developer. The documentation has to reflect these new features.

chore(documentation): add more use cases

---

.github/workflows/pull-request.yml
release.sh

This scripts helps anyone else with commiter rights to batch publish the new flashlight docker images.

chore(delivery): add a release script to increase the bus factor

---

README.md
build.sh

| Description?      | Please be specific when describing this change. What did you change? Why?
| Type?             | bug fix / improvement / new feature / refactor
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Indicate how to verify that this change works as expected.

fix(build): enhance build verbosity and documentation

---

examples/auto-install-modules/docker-compose.yml
examples/basic-example/docker-compose.yml
examples/develop-a-module/docker-compose.yml
examples/develop-prestashop/docker-compose.yml
examples/ngrok-tunnel/docker-compose.yml
examples/with-init-scripts/docker-compose.yml
examples/with-post-scripts/docker-compose.yml

An idea from Jonathan Renard, just implemented it for a better understandability once you start many examples.

fix(examples): name docker-compose projects

---

README.md
examples/auto-install-modules/README.md
examples/auto-install-modules/init-scripts/install-mock.sh
examples/basic-example/README.md
examples/develop-a-module/README.md
examples/develop-prestashop/README.md
examples/ngrok-tunnel/README.md
examples/with-init-scripts/README.md
examples/with-post-scripts/README.md

| Description?      | Some spell checks on the project :wink: 
| How to test?      | :book:

docs: Some spell checks

---

.github/workflows/docker-publish.yml
.github/workflows/nightly-cron-publish.yml
.github/workflows/pull-request.yml

Fixing issues related the the nightly build & push github action.

fix(ga): yaml formatting and syntax error

---

examples/ngrok-tunnel/docker-compose.yml
examples/nightly-example/README.md
examples/nightly-example/docker-compose.yml

| Description?      | Add more logs on nightly example & use latest on ngrock
| Type?             |  improvement
| How to test?      |

docs: Update some examples

---

docker/alpine.Dockerfile
docker/debian.Dockerfile

| Description?      | While working on the official PrestaShop docker we found out naming stages clearer. Hence this slight fix.
| Type?             | typo
| Fixed ticket?     | no
| Sponsor company   | PrestaShop SA
| How to test?      | `./build.sh` and `OS_FLAVOUR=debian ./build.sh`

fix(build): slight docker stages naming fix

---

assets/hydrate.sh
assets/patch.sh
assets/run.sh
docker/alpine.Dockerfile
docker/debian.Dockerfile

| Description?      | I could not build a prestashop flashlight instance for 1.7.6.4
| How to test?      | `PS_VERSION=1.7.6.4 ./build.sh`

fix(build): 1.7.6 were not building (ps_facetedsearch)

---

assets/alpine-base-install.sh
assets/debian-base-install.sh

| Description?      | The github-cli can really help download assets, artefacts, code, automate things. It is lightweight enough to ship it in the prestashop-flashlight toolkit.
| Fixed ticket?     | Fixes #75
| Sponsor company   | PrestaShop SA
| How to test?      | `docker run -it --rm --entrypoint sh prestashop/prestashop-flashlight -c 'gh --version'`

feat(build): add github-cli

---

assets/hydrate.sh
docker/alpine.Dockerfile
docker/debian.Dockerfile

| Description?      | Please be specific when describing this change. What did you change? Why?
| Type?             | bug fix / improvement / new feature / refactor
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Indicate how to verify that this change works as expected.

Add PS_TRUSTED_PROXIES wildcard support

---

.github/workflows/docker-publish.yml
.github/workflows/nightly-cron-publish.yml
.github/workflows/pull-request.yml

| Description?      | Please be specific when describing this change. What did you change? Why?
| Type?             | bug fix / improvement / new feature / refactor
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Indicate how to verify that this change works as expected.

fix(ci): increase job timeouts

---

README.md
assets/run.sh
examples/xdebug-prestashop/README.md
examples/xdebug-prestashop/docker-compose.yml

| Description?      | Added BLACKFIRE_ENABLED env variable and updated xdebug example
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes (https://github.com/PrestaShop/prestashop-flashlight/issues/100)
| How to test?      | Enable xdebug and try to add breakpoints

BLACKFIRE_ENABLED env variable

---

build.sh

| Description?      | Linux does support bash assoc arrays declared with "declare -A MY_VAR" however that's not the case for MacOSX. At the end the code is light like this @Alexandre-Lematre, I guess this still suits your requirements of customizing the labels.
| How to test?      | ./build.sh on MacOSX system or old bash versions.

fix(build): bash assoc array unsupported

---

.github/README_CI.md

| Description?      | Some documentation about the CI/CD
| Type?             |  improvement 
| BC breaks?        | no :x: 
| Deprecations?     | no :x:
| How to test?      |

docs: Add README for GitHub CI/CD workflows and dependencies

---

assets/alpine-base-install.sh
assets/php-configuration.sh

| Description?      | set max_input_value to 9999 into php.ini
| Fixed ticket?     | Fixe #150
| How to test?      | Run 1.6.1.11 and check if error persist into translation edit page

chore: update max_input_var to 99999 into php.ini

---

.github/workflows/docker-publish.yml

| Description?      | Adds zip source input for docker-publish workflow

Enable classic editions to be built

---

.github/workflows/docker-base-publish.yml
.github/workflows/pull-request.yml
build.sh

| Description?      | Base docker image name always computed
| Fixed ticket?     | Fixes #{[154](https://github.com/PrestaShop/prestashop-flashlight/issues/154)}

Base docker image always computed

---

.github/workflows/docker-base-publish.yml
.github/workflows/docker-publish.yml

| Description?      | Enable choosing runner when releasing

Enable runner choice

---

assets/php-configuration.sh
assets/run.sh

| Description?      | Xdebug was not completely disabled

Disables xdebug by default

---

assets/run.sh
release.sh

| Description?      | Ability to override admin email and password at runtime
| Fixed ticket?     | Fixes #{[160](https://github.com/PrestaShop/prestashop-flashlight/issues/160)}
| Sponsor company   | Prestashop

Ability to override amdin mail and password at runtime

---

docker/alpine-base.Dockerfile

| Description?      | Fixes permissions on certs for alpine so nginx can read them

Fixes permissions on certs for alpine

---

.github/workflows/docker-publish.yml

| Description?      | Fixed input not used in image publish github action

Fixed input not used in image publish github action

---

.github/workflows/pull-request.yml
build.sh
prestashop-versions.json

| Description?      | Adds an automated mecanism for retrieving the real latest Prestashop version, using a specific zip source
| Sponsor company   | Prestashop

Added a zip source mecanism for 9+ Prestashop versions
